export const FETCH_SYMBOLS = 'FETCH_SYMBOLS';
export const SET_SYMBOLS = 'SET_SYMBOLS';

export const FETCH_WATCHLIST_DATA = 'FETCH_WATCHLIST_DATA';
export const SET_WATCHLIST_DATA = 'SET_WATCHLIST_DATA';

export const ADD_WATCHLIST_ITEM = 'ADD_WATCHLIST_ITEM';
export const DELETE_WATCHLIST_ITEM = 'DELETE_WATCHLIST_ITEM';
